### ISSUE TITLE
review-index-commentとreview-insert-indexを1つにできるか

### ISSUE THREAD

**Issue by kmuto** [kmuto/review-el#16]
- review-index-commentはinteractive "P"でユーザ入力を取り込み、カーソル位置に挿入
- review-insert-indexはinteractive "r"で範囲指定を取り込み、その範囲の前に挿入

「選択されているかどうか」で挙動を振り分けることは可能？（同じショートカットキーで呼び出したい）

（ただ、たまに範囲選択が奇妙な記憶をしていることがあるような…）

**Comment by fenril058** [comment]
できると思いますが、関数名をどちらに統一すればよいでしょうか。

**Comment by fenril058** [comment]
review-insert-indexに統一したのであとは、review-index-commentを消すか残すかの決断をして、closeしてよいように思います。

**Comment by kmuto** [comment]
ありがとうございます、review-index-commentにサヨナラしたのでcloseします!
