### ISSUE TITLE
M-;でコメントを挿入できない

### ISSUE THREAD

**Issue by fenril058** [kmuto/review-el#34]
EmacsのMajor modeでは`M-;`でコメント行を挿入できるのが慣例ですが、現在は "No comment syntax defined" とEmacsから注意されてしまいます。

define-derived-modeのところに
`(setq-local comment-start "#@# ")`
として、comment-startを設定する必要があります。コメントアウトされているのはなぜでしょうか？

**Comment by kmuto** [comment]
ご指摘ありがとうございます。
なぜコメントアウトしたのかすでに忘却ですが(localなのだし、Emacsのバージョンで何か起きたわけでもないし…)、ひとまず手元でも有効化して問題なかったので有効化しました。
