### ISSUE TITLE
囲み記事のキャプションがすべて■メモ: になってしまう。

### ISSUE THREAD

**Issue by fenril058** [kmuto/review-el#38]
//note[キャプション]{ 〜 //} : ノート
//memo[キャプション]{ 〜 //} : メモ
//tip[キャプション]{ 〜 //} : Tips
のどれを使ってもキャプションが
■メモ: キャプション
になってしまいます。

**Comment by kmuto** [comment]
review-jsbookだとreviewminicolumntitleに投げてるんですがそこでmemoheadしか使ってないですね…。

が、-elの話ではないので、とりあえずissueを kmuto/review リポジトリにお願いします〜。

**Comment by fenril058** [comment]
あ、すみません、間違えてました。これは閉じて出し直します。
